SUBROUTINE ABMW(ALPHA, APRED, ACORR, BCORR, CCORR, N, IERR)

C CALCULATION OF WEIGHTS FOR FRACTIONAL ADAMS-BASHFORTH-MOULTON METHOD

IMPLICIT NONE

INTEGER	N, IERR
DOUBLE PRECISION	ALPHA
DOUBLE PRECISION	APRED(N), ACORR(n), BCORR(n), CCORR

INTEGER	J
DOUBLE PRECISION	GMALP1, GMALP2

DOUBLE PRECISION	GAMMA
EXTERNAL		GAMMA

IERR = 0
IF (ALPHA .LE. 0.D0) IERR=12
IF (IERR .NE. 0) RETURN

GMALP1 = GAMMA(ALPHA+1.D0)
GMALP2 = GMALP1*(ALPHA+1.D0)

CCORR = 1.D0/GMALP2

D0 100 J=1, N
   ACORR(J) = ((J+1)**(ALPHA+1.D0)+(J-1)**(ALPHA+1.D0)-2*J**(ALPHA+1.D0))*CCORR
   APRED(J) = (J**ALPHA-(J-1)**ALPHA)/GMALP1
   BCORR(J) = ((J-1)**(ALPHA+1.D0)-(J-1-ALPHA)*J**ALPHA)*CCORR

100 CONTINUE

RETURN
END
