DOUBLE PRECISION FUNCTION ML2P(ALPHA, BETA, X)
IMPLICIT NONE
DOUBLE PRECISION ALPHA, BETA, X

INTEGER	K, IERR
DOUBLE PRECISION	TMP, NEW, GMARG, GAMMA
EXTERNAL	GAMMA

TMP=1.D0/GAMMA(BETA)

100 GMARG=ALPHA*K+BETA
    NEW=X**K/GAMMA(GMARG)
    TMP=TMP+NEW
    K=K+1
    IF (GMARG .LT. 5.D0) GOTO 100
    IF (K .LT. 100 .AND. ABS(NEW)*1.D16 .GT. TMP) GOTO 100
    ML2P = TMP
    RETURN
    END
